name: 'Building kubernetes + helm'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Davide Frageri <davide.frag@gmail.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  URL:
    description: 'Api url'
  AUTH_URL:
    description: 'Auth url'
  FRONT_URL:
    description: 'Front url'
  TYPE:
    description: 'Deploy type'
  ENVIRONMENT:
    description: 'environment tag'
  LINK:
    description: 'Link to connect the main process'
  KUBE_CONFIG:
    description: 'Kubernetes configuration'
  KUBE_HOST:
    description: 'Kubernetes cluster host (IP only, without protocol)'
  KUBE_USERNAME:
    description: 'Kubernetes cluster username'
  KUBE_PASSWORD:
    description: 'Kubernetes cluster password'
  KUBE_CERTIFICATE:
    description: 'Cluster CA certificate'
  KUBE_NAMESPACE:
    description: 'Kubernetes namespace'
  IMAGE_LINK:
    description: 'Image github docker registry'
  IMAGE_USERS:
    description: 'Image github docker registry'
  IMAGE_PI:
    description: 'Image github docker registry'
  IMAGE_GATEWAY:
    description: 'Image gateway github docker registry'
  DOCKER_PASSWORD:
    description: 'Docker password'
  DOCKER_REGISTRY:
    description: 'Docker registry'
  DOCKER_USERNAME:
    description: 'Docker username'
  POSTGRES_USER:
    description: 'Postgres username'
  POSTGRES_PASSWORD:
    description: 'Postgres password'
  POSTGRES_DB:
    description: 'Postgres db'
  POSTGRES_VERSION:
    description: 'Postgres version'
  RABBITMQ_VHOST:
    description: 'Rabbit vhost'
  RABBITMQ_USER: 
    description: 'Rabbit user'
  RABBITMQ_PSW: 
    description: 'Rabbit psw'
  REDIS_PASSWORD:
    description: 'Redis psw'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
