name: 'Building kubernetes + helm'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Davide Frageri <davide.frag@gmail.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  KUBE_CONFIG:
    description: 'Kubernetes configuration'
  KUBE_HOST:
    description: 'Kubernetes cluster host (IP only, without protocol)'
  KUBE_USERNAME:
    description: 'Kubernetes cluster username'
  KUBE_PASSWORD:
    description: 'Kubernetes cluster password'
  KUBE_CERTIFICATE:
    description: 'Cluster CA certificate'
  KUBE_NAMESPACE:
    description: 'Kubernetes namespace'
  IMAGE_NAME:
    description: 'Image github docker registry'
  GITHUB_TOKEN:
    description: 'Github token'
  POSTGRES_USER:
    description: 'Postgres username'
  POSTGRES_PASSWORD:
    description: 'Postgres password'
  POSTGRES_DB:
    description: 'Postgres db'
  POSTGRES_VERSION:
    description: 'Postgres version
    
runs:
  using: 'docker'
  image: 'Dockerfile'
